Repository UpliftGames/wally, pull requests merged in 2024-11, with the labels that each got.

#119 Initial implementation of --locked
  CHANGELOG.md
  README.md
  src/commands/init.rs
  src/commands/install.rs
  src/commands/mod.rs
  src/commands/snapshots/libwally__commands__utils__test__snapshot_output_when_no_changes.snap
  src/commands/update.rs
  src/commands/utils.rs
  src/package_contents.rs
  src/package_name.rs
  src/resolution.rs
  test-projects/diamond-graph/root/latest/default.project.json
  test-projects/diamond-graph/root/latest/src/init.lua
  test-projects/diamond-graph/root/latest/wally.lock
  test-projects/diamond-graph/root/latest/wally.toml
  tests/integration/install.rs
Labels: enhancement, rust

#204 Handle cargo dependabot bumps
  Cargo.lock
Labels: dependencies, rust

#211 Add Homepage and Repository fields to manifests
  README.md
  src/manifest.rs
  src/test_package.rs
  test-projects/manifest-links/default.project.json
  test-projects/manifest-links/src/init.luau
  test-projects/manifest-links/wally.toml
  test-registries/primary-registry/contents/biff/manifest-links/0.1.0.zip
  test-registries/primary-registry/index/biff/manifest-links
  tests/integration/install.rs
  tests/integration/snapshots/integration__install__manifest_links.snap
  wally-registry-frontend/src/app/package/[packageScope]/[packageName]/page.tsx
  wally-registry-frontend/src/types/wally.d.ts
Labels: rust, javascript
